#datasource configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jointeams
    username: jointeams
    password: 12345678
    driver-class-name=: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true